name: AWX Control Machine Setup and Test

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  setup-awx:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Install Docker and Docker Compose
    - name: Install Docker and Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
        sudo apt-get remove -y docker docker-engine docker.io containerd runc || true
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io
        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    # Step 3: Clone the AWX repository
    - name: Clone AWX Repository
      run: |
        git clone https://github.com/ansible/awx.git
        cd awx
        git checkout 21.14.0  # Specify a stable version

    # Step 4: Deploy AWX using Docker Compose
    - name: Deploy AWX
      run: |
        cd awx
        docker-compose -f tools/docker-compose/docker-compose.yml up -d

    # Step 5: Wait for AWX to Start
    - name: Wait for AWX to Start
      run: |
        echo "Waiting for AWX to be fully operational..."
        sleep 120  # Adjust based on your environment

    # Step 6: Output AWX Access URL and Admin Credentials
    - name: Log AWX Details
      run: |
        echo "AWX Control Machine is ready for testing."
        echo "Access AWX at http://127.0.0.1:80"
        echo "Login credentials: admin / admin"
